### ISSUE TITLE
Create a logo for actinoid

### ISSUE THREAD

**Issue by thetinygoat** [actinoidlabs/actinoid#1]
If you are a designer and want to contribute to open-source, it would be really helpful if you could provide a logo for Actinoid.

#### What is actinoid
Actinoid is an upcoming fast and extensible in-memory data store.

**Comment by ShobhitRathi** [comment]
hey i would like to work on this, you can assign me

**Comment by thetinygoat** [comment]
Sure thanks a lot!

**Comment by ShobhitRathi** [comment]
hi, you can check and review the PR
